github.com:
    users:
        vinibortoletto:
            oauth_token: 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
    git_protocol: ssh
    user: vinibortoletto
    oauth_token: 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
