#!/bin/bash

# Define options
options="󰐥  Shutdown\n  Reboot\n󰍃  Logout\n  Lock"

# Get user selection using rofi
choice=$(echo -e "$options" | rofi -dmenu -p "Power Menu" -i -config ~/.config/rofi/rofidmenu.rasi)

if [[ "$choice" == "Lock" ]]; then
  ~/.config/i3/scripts/blur-lock
elif [[ "$choice" == "Shutdown" ]]; then
  poweroff
elif [[ "$choice" == "Reboot" ]]; then
  reboot
elif [[ "$choice" == "Logout" ]]; then
  loginctl terminate-session ${XDG_SESSION_ID-}
fi